services:
- type: web
  name: stickchef-ai
  env: python
  plan: free
  buildCommand: pip install -r requirements_ultra_minimal.txt
  startCommand: streamlit run app_super_minimal.py --server.port $PORT --server.address 0.0.0.0
  envVars:
  - key: PYTHON_VERSION
    value: 3.12.3
  - key: STREAMLIT_SERVER_PORT
    value: $PORT
  - key: STREAMLIT_SERVER_ADDRESS
    value: 0.0.0.0 